language: node_js
node_js:
  - "11"
  - "10"
  - "8"
  - "6"
install:
  - npm install
script:
  - npm test
  - npm run build

before_install:
  - cd website
  - npm link ../
  - npm install
  - cd ..
