name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Deploy website
        working-directory: ./website
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i
          npm run deploy
